# Generated by Django 3.1 on 2020-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='IDXXXX',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='Martril',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='RX',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
