# Generated by Django 3.1 on 2020-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200810_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.CharField(blank=True, max_length=255)),
                ('fristname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('profile', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
