# Generated by Django 2.1.15 on 2023-01-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230131_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='iduser',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iduser',
            name='iduser',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
