# Generated by Django 2.1.15 on 2023-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230131_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='iduser',
            name='lastlogin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
