# Generated by Django 2.1.15 on 2023-01-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_iduser_lastlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iduser',
            new_name='UserID',
        ),
    ]
