# Generated by Django 2.1.15 on 2023-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230131_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalid', models.CharField(blank=True, max_length=50)),
                ('fristname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=25)),
                ('lastlogin', models.CharField(blank=True, max_length=25, null=True)),
                ('profile', models.FileField(blank=True, default='', null=True, upload_to='documents/')),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='IDXXXX',
            new_name='docdata',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='RX',
            new_name='docid',
        ),
    ]
