# Generated by Django 2.1.15 on 2023-02-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230201_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_data',
            name='lastlogin',
        ),
        migrations.RemoveField(
            model_name='personal_data',
            name='profile',
        ),
    ]
